{% set name = "MatrixSwitch" %}
{% set version = "1.0.0" %}
{% set build = 2 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/ElectronicStructureLibrary/omm-bundle/-/archive/v{{ version }}/omm-bundle-v{{ version }}.tar.gz
  sha256: 815f849d4a603383e6553db4e97fe695882b40e4bbc6f33577bc2556166949af
  patches:
    - perl.patch

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win]
  script:
    - set -ex
    - export FFLAGS="${FFLAGS} -fallow-argument-mismatch"  # [linux or (osx and arm64)]
    - export OPAL_PREFIX=$PREFIX  # [mpi == 'openmpi']
    - export CC="mpicc" FC="mpifort"  # [mpi != 'nompi']
    - pushd {{ name }} && bash autogen.sh && popd
    - LINALG_LIBS="-llapack -lblas"
    - LINALG_LIBS="-lscalapack ${LINALG_LIBS}"  # [mpi != 'nompi']
    - {{ name }}/configure --prefix=$PREFIX LINALG_LIBS="${LINALG_LIBS}"
    - make -j ${CPU_COUNT:-1}
    - make install

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

  run_exports:
    - {{ pin_subpackage('matrixswitch', max_pin='x.x') }}
  {% if mpi != "nompi" %}
    - {{ name|lower }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - libtool
    - automake
    - autoconf
    - gnuconfig  # [unix]
    - make
    - perl
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - {{ mpi }}  # [mpi == "openmpi" and build_platform != target_platform]
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - scalapack  # [mpi != 'nompi']
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - scalapack  # [mpi != 'nompi']

test:
  requires:
    - pkg-config
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}
    - pkg-config {{ name }} --exact-version {{ version }}

about:
  home: https://gitlab.com/ElectronicStructureLibrary/omm-bundle
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - {{ name }}/COPYING
  summary: Intermediary interface layer between high-level routines for physics-related algorithms and low-level routines dealing with matrix storage and manipulation
  doc_url: https://esl.cecam.org/software/matrixswitch/
  dev_url: https://gitlab.com/ElectronicStructureLibrary/omm-bundle/-/tree/master/MatrixSwitch

extra:
  recipe-maintainers:
    - awvwgk
